### ISSUE TITLE
[📚] Improve about

### ISSUE THREAD

**Issue by dylancom** [invertase/react-native-google-ads#11]
I think that for the discoverability of this package, it would be better if the about mentions "AdMob". (As that is still what the monetization platform is called).

My suggestion is to change:
⚠️ WIP ⚠️ - React Native Google Ads is a module connecting you to Google Ads services; a light-weight JavaScript layer connecting you to the native Google-Mobile-Ads SDKs for both iOS and Android.

To:
⚠️ WIP ⚠️ - React Native Google Ads allows you to monetize your app with AdMob; a React Native wrapper around the native Google-Mobile-Ads SDKs for both iOS and Android.

See for e.g. the intro on:
https://developers.google.com/admob/ios/quick-start

**Comment by mikehardy** [comment]
Interesting - their branding is inconsistent, but totally works for me. Done - also added tags
