### ISSUE TITLE
Rewarded value can be nil

### ISSUE THREAD

**Issue by TaylorDale** [invertase/react-native-google-ads#3]
https://github.com/invertase/react-native-google-ads/blob/105abb74d3b44692b180613aec86ce1e57702e9b/ios/RNGoogleAds/RNGoogleAdsRewardedModule.m#L107

The rewarded values can be nil on iOS when using admob mediation with a network such as FAN that does not allow you to provide these values. This causes an app crash, has been happening to many users.

**Comment by mikehardy** [comment]
Oh my - thanks for reporting that.
Are you actually using this module already? Just curious - I tried to post it up as soon as it was at the "compiles, might work..." state, but if you're already using it I'm actually surprised it is working, I was sure as soon as I got the new e2e tests up for it I'd find a bunch of immediate crashes (software being software...)

**Comment by TaylorDale** [comment]
Yeah thanks for the work on this one seems like some big changes from the upstream... I'm not using this new module yet, still on the firebase version of it but the code is the same so figured I'd report the bug here :)
