### ISSUE TITLE
[🐛] `testDeviceIdentifiers` param has no effect on Android

### ISSUE THREAD

**Issue by birdofpreyru** [invertase/react-native-google-ads#35]
Because #30 released as v2.0.0 only covered iOS side of `testDevices` &rarr; `testDeviceIdentifiers` replacement, it also removed `testDevices` from type definitions in JS code, and updated the documentation, but did not bother to update Android code to be on par :(

P.S.: Ok, I see that fixing it seems to be already in progress in PR #32, but... something went wrong here that #30 was released at all before #32 was ready :(

**Comment by mikehardy** [comment]
"something went wrong" --> I appreciate the testing but it is not that "something went wrong" it is that the repository is still quite raw. Testing reports are great. PRs are great, but I wouldn't spend too much time wondering about our motives here.

Please note you and I both are working on the weekend to get things fixed yes? It will settle down shortly, if it is bothersome to you to discover problems until it settles down I'd suggest waiting a week at least.

**Comment by mikehardy** [comment]
Oh, alternatively, use the v1.x releases ;-), that was a breaking change and v1.x still has the old style that didn't take the property break

**Comment by mikehardy** [comment]
Second alternative - different direction then rolling back - is rolling forward, we generate a patch set on PRs and this one should have the results of the current android work shortly when CI is done chewing on them https://github.com/invertase/react-native-google-ads/actions/runs/1569354147

**Comment by birdofpreyru** [comment]
Sorry @mikehardy , I appreciate your work, I was just a bit unprepared and annoyed by your versioning approach. When I see v2, or v3 my base expectations are similar to what I get from, say webpack@5, react-router@6 (in the sence that once they release x.0.0, that is production ready, beside maybe some corner case failures).

**Comment by mikehardy** [comment]
No problems, and I reiterate that I really appreciate you are even here, testing this. We will get stabilized, once we get past this initial repo bringup I actually expect every single release to be stable, with changelogs that you can trust without question. Just a bit of a rocky launch as we re-hosted, then immediately had to take two breaking change SDK upgrades as sort of a minimum just to get moving.
