### ISSUE TITLE
Initialize/Start not called

### ISSUE THREAD

**Issue by TaylorDale** [invertase/react-native-google-ads#4]
Hi again - apologies for polluting the new repo with issues... 

It would be very helpful if there was a method to call initialize() (android) and start() (iOS) on the Admob SDK. Admob ads work fine if this is not called, but most mediation (AdColony, FAN for example) will not work fullstop if these respective functions are not called (Worth noting, Unity ads *does* work without calling this but that is the only one I've found so far). The mediation test suite also will fail to launch if these haven't been called. It makes for a really hard-to-debug mediation situation as when init() isn't called there is not much to tell you that is the problem.

I've just ended up placing these methods in my AppDelegate onLaunch/Activity OnStart methods but it would be great to be able to call them from RN.

**Comment by mikehardy** [comment]
Very interesting! Will keep this in the queue. I've been traveling which put the extraction/bring-up of this code from react-native-firebase on hold for a week or so but I'm about to get back to it this week. First step will be a straight extraction / re-vivification with no breaking changes or features other than symbol names moving around.

Then I'll forward port to new SDKs

Then I'll scan the list as things come in here (like this one) and try to get to them, or perhaps you can help with a PR once the repo is actually alive and kicking 🙏 😄

**Comment by TaylorDale** [comment]
Awesome thanks for the hard work put in to these libs. Would love to submit a PR for this one - will see if I get some free time.

**Comment by mikehardy** [comment]
@TaylorDale these are about to launch...

**Comment by TaylorDale** [comment]
@mikehardy thanks mate appreciate all the hard work!
