### ISSUE TITLE
[iOS] A bug in error handling

### ISSUE THREAD

**Issue by birdofpreyru** [invertase/react-native-google-ads#45]
The following call crashes entire host app with obscure error message _"[__NSPlaceholderDictionary initWithObjects:forKeys:count:] attempt to insert nil object from objects[2]"_ if wrong ad unit ID was provided to the interstitial's **createForAdRequest()** method:
https://github.com/invertase/react-native-google-ads/blob/5ebaaeead16a00511b49213e8da309b9db31a396/ios/RNGoogleAds/RNGoogleAdsCommon.m#L131-L136

In that case the following handler is envoked with nil `ad` argument, which results in nil `adUnitId` inside the sendAdEvent() method above.
https://github.com/invertase/react-native-google-ads/blob/5ebaaeead16a00511b49213e8da309b9db31a396/ios/RNGoogleAds/RNGoogleAdsInterstitialModule.m#L74

I guess, that nil should be correctly captured, and the error should be gracefully handled and reported to the developer.

P.S.: it seems **3.2.0** works fine for me on Android, and with this small problem figured out, it also seems to work on iOS (I use Banner, Interstitials, and that ad consent stuff). Hooray! Many thanks for finally making this lib functional! :)

P.S.S.: Also, not sure because of this library, or the main RN-firebase, the iOS build fails if no `firebase.json` file is present in the project root (I ended up with that file empty, so wanted to remove it). Works fine without it for Android build.

**Comment by dylancom** [comment]
Good catch! This must be caused by ad.adUnitID not existing when no ad could be loaded. (https://github.com/invertase/react-native-google-ads/blob/5ebaaeead16a00511b49213e8da309b9db31a396/ios/RNGoogleAds/RNGoogleAdsInterstitialModule.m#L81) It can be replaced by using the adUnitId argument.
