### ISSUE TITLE
[🐛] 🔥  IOS [googleAds/unknown error] rewarded ad 'The provided view controller is already presenting another view controller'

### ISSUE THREAD

**Issue by danilaberentsev** [invertase/react-native-google-ads#47]
## Issue

I'm trying to get rewarded ad on IOS, and after it loaded and invoked with rewarded.show(), I'm getting [googleAds/unknown error] when using real/test unit ids on emulator, and test unit id on a real device, the only exception is when I'm using real unit id on the real device I'm getting [googleAds/no-fill] error on ad load (screens below). On android everything working fine it seems.
Both ios and android devices were added on admob console as test devices.

I used another library with the same unit ids from admob and it worked both for ios and android, but that library didn't provide server-side verification.

**This is effect initializing rewarded ad**
![](https://cdn.discordapp.com/attachments/663561287023984650/925362045602369566/unknown.png)

**This is onPress handler**
![](https://cdn.discordapp.com/attachments/663561287023984650/925361765599047680/image.png)

**IOS console output on emulator**
with test unit id:
![](https://cdn.discordapp.com/attachments/663561287023984650/925363020585123860/image.png)
with real ios unit id:
![](https://cdn.discordapp.com/attachments/663561287023984650/925363020803219516/image.png)

**IOS console output on a real device specified as a test device on admob console**
with test unit id:
![](https://cdn.discordapp.com/attachments/663561287023984650/925363020585123860/image.png)
with real ios unit id:
![](https://cdn.discordapp.com/attachments/663561287023984650/925364832402821210/image.png)

**Android console output on emulator**
works fine both with test id and real id, and showing an advert
![](https://media.discordapp.net/attachments/663561287023984650/925365893079367690/image.png)
![](https://media.discordapp.net/attachments/663561287023984650/925365893268119592/image.png)
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "samplename",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "adb reverse tcp:8081 tcp:8081 && adb reverse tcp:3001 tcp:3001 && react-native start",
    "start": "react-native start",
    "server": "nodemon babel-node mock_server.js",
    "port": "adb reverse tcp:8081 tcp:8081 && adb reverse tcp:3001 tcp:3001",
    "test": "jest",
    "lint": "eslint .",
    "pod": "npx pod-install",
    "postinstall": "npx jetify"
  },
  "dependencies": {
    "@invertase/react-native-apple-authentication": "^2.1.2",
    "@invertase/react-native-google-ads": "^3.2.0",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-firebase/app": "^12.1.0",
    "@react-native-firebase/auth": "^12.1.0",
    "@react-native-google-signin/google-signin": "^6.0.1",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/native": "^6.0.0-next.15",
    "@react-navigation/native-stack": "^6.0.0-next.9",
    "axios": "^0.21.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "qs": "^6.10.1",
    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-bootsplash": "^3.2.4",
    "react-native-config": "^1.4.2",
    "react-native-device-info": "^8.1.4",
    "react-native-fbsdk-next": "^4.3.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-get-random-values": "^1.7.0",
    "react-native-localize": "^2.1.1",
    "react-native-material-ripple": "^0.9.1",
    "react-native-modal": "^13.0.0",
    "react-native-paper": "^4.9.2",
    "react-native-payments": "^0.8.4",
    "react-native-reanimated": "^2.2.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.4.0",
    "react-native-svg": "^12.1.1",
    "react-native-toast-notifications": "^3.2.3",
    "react-native-vector-icons": "^8.1.0",
    "react-native-video": "^5.2.0",
    "react-redux": "^7.2.4",
    "redux": "^4.1.0",
    "redux-saga": "^1.1.3",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "^7.2.0",
    "eslint-config-airbnb": "18.2.1",
    "eslint-import-resolver-babel-module": "^5.3.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^1.7.0",
    "express": "^4.17.1",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "nodemon": "^2.0.12",
    "react-test-renderer": "17.0.1",
    "reactotron-react-native": "^5.0.0",
    "reactotron-redux": "^3.1.3",
    "reactotron-redux-saga": "^4.2.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

#### `app.json`:

```json
{
  "name": "samplename",
  "displayName": "samplename",
  "react-native-google-ads": {
    "android_app_id": "android_unit_id",
    "ios_app_id": "ios_unit_id"
  }
}

```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
# inhibit_all_warnings! - ignore all xcode warnings

target 'pro_appetit' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'GoogleSignIn', '~> 5.0.0'

  target 'pro_appetitTests' do
    inherit! :complete
    # Pods for testing
  end


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
    end
  end
end

```

---
</p>
</details>

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "20.1.5948944"
        googlePlayServicesAuthVersion = "16.0.1"
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")
        classpath 'com.google.gms:google-services:4.3.8'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        mavenCentral()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"

import com.android.build.OutputFile


project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

project.ext.vectoricons = [
    iconFontNames: [ 'MaterialIcons.ttf', 'FontAwesome.ttf', 'MaterialCommunityIcons.ttf' ]
]
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.pro_appetit"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 2
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        defaultConfig.versionCode * 1000 + versionCodes.get(abi)
            }

        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.google.android.gms:play-services-wallet:17.0.0'
    implementation 'com.android.support:appcompat-v7:24.1.1'

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

apply plugin: "com.google.gms.google-services"

```

#### `android/settings.gradle`:

```groovy
rootProject.name = 'samplename'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.pro_appetit">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <meta-data
        android:name="com.google.android.gms.wallet.api.enabled"
        android:value="true" />
      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
      </activity>
      <activity
        android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
        android:theme="@style/BootTheme"
        android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
      </activity>
    </application>
</manifest>

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.3
    CPU: (8) arm64 Apple M1
    Memory: 203.09 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.10.0 - /opt/homebrew/bin/npm
    Watchman: 2021.12.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-S | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
- **Are you using `TypeScript`?**
  - N

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by dylancom** [comment]
Are you sure that it works fine in a different lib? Because the no ad inventory error is not related to this package (error coming from the native sdk).

This can happen due to different reasons. Sometimes test ads only show up on a real device, AdMob is also requiring an extra entry in your app-ads.txt https://developers.google.com/admob/ios/test-ads

**Comment by danilaberentsev** [comment]
@dylancom thanks for the fast answer!

Yeah, I'm pretty sure, but I can double-check.

I'm didn't add app-ads.txt, is it mandatory? My app is only in test environment and not in the app/google stores.
Shouldn't I at least get test ad with TestIds.REWARDED? I'm still getting this unknown error with test unit ids, both on real device and emulator.

and it's already far from 24h passed

**Comment by dylancom** [comment]
It's mandatory if you not register test devices. I for example am not able to get test ads filled on an Android simulator, but on a real Android device I can display test ads. On the other hand it works fine for me on the iOS simulator.

**Comment by danilaberentsev** [comment]
Well, I did register test devices, though.

So, I installed back that package https://github.com/react-native-admob/admob and tested a little.
And I manage to get rewarded ads shown with their TestIds on a real device. Also works on emulator with real devices ids, and test ids. On real device and real id it shows something similar I guess [AdError: Request Error: No ad to show.]

So at least it shows test ads and real ads on the emulator

**Comment by dylancom** [comment]
Did you try it with the app idd i sent? Will have time later to see what that lib does differently.

Verstuurd vanaf mijn iPhone

**Comment by danilaberentsev** [comment]
@dylancom 

Tried your test app id for ios, and both emulator and real device return the same [unknown error]
![](https://cdn.discordapp.com/attachments/663561287023984650/925388915374948353/unknown.png)

**Comment by dylancom** [comment]
And are interstitials working fine for you?

**Comment by danilaberentsev** [comment]
> And are interstitials working fine for you?

Nope, same thing but without reward object (currently with your app id)
![](https://cdn.discordapp.com/attachments/663561287023984650/925394953323044924/unknown.png)

**Comment by dylancom** [comment]
Did you added testdevices?

https://docs.page/invertase/react-native-google-ads#configure-outbound-requests

Verstuurd vanaf mijn iPhone

**Comment by danilaberentsev** [comment]
got the banner though

**Comment by danilaberentsev** [comment]
> Did you added testdevices? https://docs.page/invertase/react-native-google-ads#configure-outbound-requests Verstuurd vanaf mijn iPhone
> […](#)
> Op 28 dec. 2021 om 15:30 heeft Danil Tereschenko ***@***.***> het volgende geschreven: ﻿ And are interstitials working fine for you? Nope, same thing but without reward object (currently with your app id) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

give me a moment

**Comment by danilaberentsev** [comment]
> Did you added testdevices? https://docs.page/invertase/react-native-google-ads#configure-outbound-requests Verstuurd vanaf mijn iPhone
> […](#)
> Op 28 dec. 2021 om 15:30 heeft Danil Tereschenko ***@***.***> het volgende geschreven: ﻿ And are interstitials working fine for you? Nope, same thing but without reward object (currently with your app id) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

give me a moment
oops I fatfingered close issue

**Comment by danilaberentsev** [comment]
@dylancom 

I indeed forget to add my test devices ids, there was only EMULATOR (sorry about that), but sadly it didn't change anything, still getting an unknown error, tried all kinds of cases

So far the only thing working is a banner with TestIds.BANNER

**Comment by dylancom** [comment]
Hmm not sure what goes wrong on your side.
I just created a new React Native project, installed the latest react-native-google-ads @ 3.2.1 and copied the code from our example: https://docs.page/invertase/react-native-google-ads/displaying-ads

When running it on an iOS simulator it will show a fullscreen test ad.
I have no test devices configured and use test admob app id's, so no real AdMob account is involved.
My app.json:
```
{
  "name": "GoogleAdsTest",
  "displayName": "GoogleAdsTest",
  "react-native-google-ads": {
    "android_app_id": "ca-app-pub-3940256099942544~3347511713",
    "ios_app_id": "ca-app-pub-3940256099942544~1458002511"
  }
}
```

**Comment by dylancom** [comment]
Ah I see what's going wrong. You're using the same testad id for development as production.
You are passing `unitIds[Platform.OS]` which should be:
`__DEV__
  ? TestIds.REWARDED
  : unitIds[Platform.OS]`
  
  Please read our docs.

**Comment by danilaberentsev** [comment]
It doesn't matter which ad unit id I use, I tested both with test id and real id, you can see console outputs in my first message, it also returns an unknown error.

I again tried app ids you provided
```json
"react-native-google-ads": {
  "android_app_id": "ca-app-pub-3940256099942544~3347511713",
  "ios_app_id": "ca-app-pub-3940256099942544~1458002511"
}
```
Still no luck same [Error: [googleAds/unknown] An unknown error occurred.] with TestIds.REWARDED when I press on rewarded.show() (tried both emulator and device)

also here is initialize output I didn't send
```json
[
  {"description": "<GADAdapterStatus: 0x600000d316e0; state = Not Ready;No such adapter in the application.>", "name": "GADMediationAdapterAppLovin", "state": 0},
  {"description": "<GADAdapterStatus: 0x600000d36160; state = Not Ready;No such adapter in the application.>", "name": "SampleCustomEventRewarded", "state": 0},
  {"description": "<GADAdapterStatus: 0x600000c90a80; state = Ready>", "name": "GADMobileAds", "state": 1},
  {"description": "<GADAdapterStatus: 0x600000d35e90; state = Not Ready;No such adapter in the application.>", "name": "GADMediationAdapterAdColony", "state": 0},
  {"description": "<GADAdapterStatus: 0x600000d31770; state = Not Ready;No such adapter in the application.>", "name": "GADMediationAdapterVungle", "state": 0},
  {"description": "<GADAdapterStatus: 0x600000d31710; state = Not Ready;No such adapter in the application.>", "name": "GADMediationAdapterSample", "state": 0},
  {"description": "<GADAdapterStatus: 0x600000d38f00; state = Not Ready;No such adapter in the application.>", "name": "MediationExample.SampleCustomEventNativeAdSwift", "state": 0},
  {"description": "<GADAdapterStatus: 0x600000d35f80; state = Not Ready;No such adapter in the application.>", "name": "GADMediationAdapterTapjoy", "state": 0},
  {"description": "<GADAdapterStatus: 0x600000d38ed0; state = Not Ready;No such adapter in the application.>", "name": "MediationExample.SampleCustomEventInterstitialSwift", "state": 0},
  {"description": "<GADAdapterStatus: 0x600000d35f50; state = Not Ready;No such adapter in the application.>", "name": "SampleCustomEventBanner", "state": 0},
  {"description": "<GADAdapterStatus: 0x600000d35fb0; state = Not Ready;No such adapter in the application.>", "name": "SampleCustomEventInterstitial", "state": 0},
  {"description": "<GADAdapterStatus: 0x600000d35620; state = Not Ready;No such adapter in the application.>", "name": "MediationExample.SampleCustomEventBannerSwift", "state": 0},
  {"description": "<GADAdapterStatus: 0x600000d35710; state = Not Ready;No such adapter in the application.>", "name": "SampleCustomEventRewardedBasedVideoSwift", "state": 0},
  {"description": "<GADAdapterStatus: 0x600000d360d0; state = Not Ready;No such adapter in the application.>", "name": "SampleCustomEventNativeAd", "state": 0},
  {"description": "<GADAdapterStatus: 0x600000d31740; state = Not Ready;No such adapter in the application.>", "name": "GADMediationAdapterInMobi", "state": 0}
]
```

**Comment by dylancom** [comment]
Are you now including multiple admob libraries in your project? There might be some interference.
The best option would be to open the project in Xcode, edit RNGoogleAdsCommon.m to log the `error.code`.
See: https://github.com/invertase/react-native-google-ads/blob/291e50479ad12ade313ebfa86d47cb9af4d8cc57/ios/RNGoogleAds/RNGoogleAdsCommon.m#L91

So right now it's staying "unknown" as the error is not one of: GADErrorInvalidRequest, GADErrorNoFill, GADErrorNetworkError, GADErrorInternalError.

**Comment by mikehardy** [comment]
@dylancom this is likely something project-specific, right? So in the end there is only so much we can do. However, issues like these are most useful at the maintainer level for learning what sort of diagnostic output is important for self-diagnosis for users - anything like the comment you mentioned above should probably be added to the library so that users may simply access the information directly and ideally not clutter the issues list

**Comment by dylancom** [comment]
@mikehardy we should definitely extend our error handling to check for all Error Codes mentioned in: https://developers.google.com/admob/ios/api/reference/Enums/GADErrorCode

**Comment by dylancom** [comment]
@mikehardy we should definitely extend our error handling to check for all Error Codes mentioned in: https://developers.google.com/admob/ios/api/reference/Enums/GADErrorCode
As many errors are currently not handled and leaving the user with an "unknown" error log.

**Comment by dylancom** [comment]
@mikehardy made a PR that adds the remaining error codes: https://github.com/invertase/react-native-google-ads/pull/49

**Comment by dylancom** [comment]
@danilaberentsev could you install `3.3.0`? I added additional error codes that weren't included before and should probably catch your error. Please run a pod install after upgrading.

**Comment by danilaberentsev** [comment]
> @danilaberentsev could you install `3.3.0`? I added additional error codes that weren't included before and should probably catch your error. Please run a pod install after upgrading.

yes, give me a moment.

I just make a new clean project with react-native init and both test id and my unit ids from admob working fine on ios.

Also, you asked if I used 2 libraries at once, the answer is no, I uninstalled one before using other

**Comment by danilaberentsev** [comment]
still getting an unknown error, could it be some kind of caching problem?

![image](https://user-images.githubusercontent.com/37038091/147670517-a611118e-fcae-4917-85ad-933a3e2517f1.png)
![image](https://user-images.githubusercontent.com/37038091/147670563-f703853a-650d-4837-81e9-d4d156f88c2a.png)

**Comment by mikehardy** [comment]
It is always possible there is some caching issue :-), I recommend `npx react-native-clean-project` for a very thorough (but also unfortunately "expensive" in terms of network traffic etc) rebuild of local state when I'm not sure personally

**Comment by danilaberentsev** [comment]
So I made npx react-native-clean-project. It also updated some of google pods versions, and after a long indexing/building I'm still getting this unknown error message

![image](https://user-images.githubusercontent.com/37038091/147674377-bce65a66-837a-49ff-a1a3-bb817483afa0.png)

it's leading here, don't know if it's helping
![image](https://user-images.githubusercontent.com/37038091/147674582-3da3238e-9ef0-44b5-8faf-2e78a521b0c0.png)

**Comment by danilaberentsev** [comment]
and this is how errors part in `react-native-google-ads/ios/RNGoogleAds/RNGoogleAdsCommon.m` looks like

```
+ (NSDictionary *)getCodeAndMessageFromAdError:(NSError *)error {
  NSString *code = @"unknown";
  NSString *message = @"An unknown error occurred.";

  if (error.code == GADErrorInvalidRequest) {
    code = @"invalid-request";
    message = @"The ad request was invalid; for instance, the ad unit ID was incorrect.";
  } else if (error.code == GADErrorNoFill) {
    code = @"no-fill";
    message = @"The ad request was successful, but no ad was returned due to lack of ad inventory.";
  } else if (error.code == GADErrorNetworkError) {
    code = @"network-error";
    message = @"The ad request was unsuccessful due to network connectivity.";
  } else if (error.code == GADErrorServerError) {
    code = @"server-error";
    message = @"The ad server experienced a failure processing the request.";
  } else if (error.code == GADErrorOSVersionTooLow) {
    code = @"os-version-too-low";
    message = @"The current device’s OS is below the minimum required version.";
  } else if (error.code == GADErrorTimeout) {
    code = @"timeout";
    message = @"The request was unable to be loaded before being timed out.";
  } else if (error.code == GADErrorMediationDataError) {
    code = @"mediation-data-error";
    message = @"The mediation response was invalid.";
  } else if (error.code == GADErrorMediationAdapterError) {
    code = @"mediation-adapter-error";
    message = @"Error finding or creating a mediation ad network adapter.";
  } else if (error.code == GADErrorMediationInvalidAdSize) {
    code = @"mediation-invalid-ad-size";
    message = @"Attempting to pass an invalid ad size to an adapter.";
  } else if (error.code == GADErrorInternalError) {
    code = @"internal-error";
    message = @"Something happened internally; for instance, an invalid response was received from "
              @"the ad server.";
  } else if (error.code == GADErrorInvalidArgument) {
    code = @"invalid-argument";
    message = @"Invalid argument error.";
  } else if (error.code == GADErrorReceivedInvalidResponse) {
    code = @"received-invalid-response";
    message = @"Received invalid response.";
  } else if (error.code == GADErrorMediationNoFill) {
    code = @"mediation-no-fill";
    message = @"A mediation ad network adapter received an ad request, but did not fill. The "
              @"adapter’s error is included as an underlyingError.";
  } else if (error.code == GADErrorAdAlreadyUsed) {
    code = @"ad-already-used";
    message = @"Will not send request because the ad object has already been used.";
  } else if (error.code == GADErrorApplicationIdentifierMissing) {
    code = @"application-identifier-missing";
    message = @"Will not send request because the application identifier is missing.";
  }

  return @{
    @"code" : code,
    @"message" : message,
  };
}
```

**Comment by dylancom** [comment]
@danilaberentsev That's def the last version. We now released 3.4.0 that doesn't contain custom messages anymore and should always output the error message sent by the google mobile ads sdk.

**Comment by danilaberentsev** [comment]
So, now things got clear
Now I'm getting this error `NativeError: [googleAds/unknown] The provided view controller is already presenting another view controller. `

The show ad button was actually rendered in a react-native-modal, which I couldn't guess was the case since it worked on android, and other library had no problems with that. So seems like you can't have both react-native-modal and rewarded ads at the same time.

**Comment by danilaberentsev** [comment]
thanks for helping, guys

**Comment by TaylorDale** [comment]
> The show ad button was actually rendered in a react-native-modal,

Wish I'd read this earlier so I could have helped you - I've run into this issue many times before, before realising the solution! Seems everyone puts their view rewarded ad buttons in modals.

**Comment by hannojg** [comment]
Hm, is there no workaround? The issue also happens when using `react-navigation`.
For iOS, I would have to close the modal, show the ad, and reopen the modal, which would be weird UX, as the user will be able to see that the modal gets closed :/
