### ISSUE TITLE
🔥[🐛] Parameter must be descendant of view crash

### ISSUE THREAD

**Issue by TaylorDale** [invertase/react-native-google-ads#55]
Code in AdmobBanner view manager potentially causing app crashes, solution may need to be inserted around this line:

https://github.com/invertase/react-native-google-ads/blob/2e5987aee8fa34855c657950ae36323a136b3aae/android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsBannerAdViewManager.java#L116

See discussion here ( https://github.com/facebook/react-native/issues/32649#issuecomment-990968256 ), where there has been a fix suggested for the firebase/admob 11.5.0 release. Code appears to be the same/similar here, worth adding this fix?

**Comment by mikehardy** [comment]
Thanks for logging this, especially with the detailed references. Indeed, the code is right from react-native-firebase/admob 11.5 so unless the code was specifically altered here (check git blame for the forward port changes) then it'll be the same and have the same problems. 

Care to post a PR with the change? Looks like a one-liner...

**Comment by TaylorDale** [comment]
On it!
