### ISSUE TITLE
[🐛] Empty ad banner sizing in v4 beta version on Android

### ISSUE THREAD

**Issue by birdofpreyru** [invertase/react-native-google-ads#60]
Hey @dylancom , I just have briefly tried 4.0.1 beta version in my project on Android, it seems it alters the sizing of empty banner compared to v3.4.0 version (and I am using a locally customized 3.4.0 variant, which includes the patch I submitted yesterday, so that should not be relavant):
- In 3.4.0 `<BannerAd>` has the same size (requested by `size` prop) no matter whether the ad is currenly loaded or not.
- In 4.0.1 `<BannerAd>` seems to collapse to zero size when no ad is loaded yet.

I'll probably investigate further sometime later, but just wanted to ping you in case you recognize the issue/fix from this description.

**Comment by dylancom** [comment]
Thanks for the report.
The onNativeEvent code slightly changed, that might be causing it.
https://github.com/invertase/react-native-google-ads/compare/beta#diff-841a5420c78698bad06317f0d0490c9dad208e98f7b29a4f12b41f87d1df63afR78

**Comment by dylancom** [comment]
Found it, on the native side we are sending "onSizeChange" events while in the onNativeEvent function it was checking for "onSizeChange**d**". Thanks for the catch!
